pipeline {
    agent any

    stages {
        stage('Checkout') {
            steps {
                checkout scm
            }
        }

        stage('Build') {
            steps {
                dir('dms.kalari') {
                    sh 'mvn clean package -DskipTests'
                }
            }
        }

        stage('Archive Artifact') {
            steps {
                dir('dms.kalari') {
                    archiveArtifacts artifacts: 'target/*.jar', fingerprint: true
                }
            }
        }

        // Optional testing
        /*
        stage('Test') {
            steps {
                dir('dms.kalari') {
                    sh 'mvn test'
                }
            }
        }
        */
    }
}
